#!/usr/bin/env fish

# TODO allow passing in different bases
# (also useful for pull request creation)
# branch (issue) | target branch | milestone (id)
set issue (~/code/zenflow/next.py)
set base_branch develop

cd ~/code/clint

if [ -z "$issue" ]
    # TODO refactor
    echo 'No issue. Could move top backlog ticket'
    # set issue (~/code/zenflow/start.py)
else
    echo "Issue $issue"
end

set target_branch razzi/$issue
set current_branch (git symbolic-ref --short HEAD)

if test "$current_branch" = "$target_branch"
    echo good to go
else if [ (git branch --list $target_branch) ]
    git checkout $target_branch
else
    git fetch origin $base_branch
    git checkout -b $target_branch origin/$base_branch
    and git push -u origin $target_branch
end
