#!/usr/bin/env fish

# TODO allow passing in different bases
# (also useful for pull request creation)
# branch (issue) | target branch | milestone (id)
set issue (~/code/zenflow/next.py)
set base_branch develop

cd ~/code/clint

if [ -z "$issue" ]
    # TODO refactor
    echo 'No issue. Could move top backlog ticket'
    exit
    # set issue (~/code/zenflow/start.py)
else
    echo "Issue $issue"
end

set target_branch razzi/$issue
set current_branch (git symbolic-ref --short HEAD)

if test "$current_branch" = "$target_branch"
    echo good to go
else if [ (git branch --list $target_branch) ]
    git checkout $target_branch
else
    # todo fetch automatically (cron)
    # git fetch origin $base_branch
    git checkout develop
    git checkout -b $target_branch
    # blarg bogus - could stash and pop ;_;
    # git reset --hard origin/$base_branch

    # TODO this isn't working and is super dangerous :X
    # hopefully matching current will work for setting upstream
    # git checkout -b $target_branch origin/$base_branch
    # and git push -u origin $target_branch
end
